### ISSUE TITLE
Question regarding compilation

### ISSUE THREAD

**Issue by peddamat** [anishathalye/periscope#2]
Thank you for putting together this great utility!

I'm very rusty at Go, do you mind telling me what the command to compile a binary is?

Visual Studio code is doing some magic to build the application, but I'm unable to manually produce a binary, myself.

Best,

Sam

**Comment by anishathalye** [comment]
In the directory of the project, `go build ./...` or `go install ./...` is probably what you want.

**Comment by peddamat** [comment]
Thank you for the pointer!  Here's what worked for me:

Build 'psc' binary: go build ./cmd/psc/...
Run 'psc' without creating binary: go run ./cmd/psc/...

Hope this helps other folks getting started on this codebase.  Thanks again, Anisha!

**Comment by anishathalye** [comment]
Great! Let me know if you have any feedback on how Periscope runs on Windows.
