### ISSUE TITLE
question: what mechanisms are used to determine a duplicate?

### ISSUE THREAD

**Issue by bobbintb** [anishathalye/periscope#5]
Like you, I too was having an issue finding a dupe program that fit with what I wanted. I thought of making my own as well but have too many other projects. Periscope seems pretty in line with the philosophy I was thinking but I'm just wondering how does it determine dupes? Most just use a hash comparison but others use a combination of techniques that improves performance.

**Comment by anishathalye** [comment]
Periscope's algorithm for finding duplicates is [pretty simple](https://github.com/anishathalye/periscope/blob/609be2cba44d74fdeedc40a1a9fe2b8840417ea0/scan.go). Right now, it's:

1. Group by file size, remove singletons
2. Group by hash of a prefix (first 4K) of remaining files, remove singletons
3. Compute full hash of remaining files (using blake2b, a fast cryptographic hash function)

This is done using many threads to try to maximize IO throughput. Periscope doesn't currently have any particularly fancy systems optimizations (e.g. it doesn't do fancy stuff based on whether it's an SSD or spinning disk, it doesn't do anything special if it's scanning paths that span multiple devices versus a single one, etc.).

**Comment by anishathalye** [comment]
Feel free to reopen if you have any other questions
